---
- name: Deploy secondary cloudflared tunnel for high availability
  # When I add a new service to the nginx config, I re-deploy with ansible.
  # Since it restarts both containers, including cloudflared, if something is wrong with nginx config, tunnel will go down.
  # To prevent this, I am using this tunnel to have uninterrupted access
  hosts: rasp
  become: true
  vars:
    base_dir: "/opt/services/cloudflared-backup"

  tasks:
    - name: Ensure directories exist
      file: 
        path: "{{ base_dir }}" 
        state: directory
        mode: '0755'
        owner: root
        group: root

    
    - name: Copy Production Environment file
      copy:
        src: ./.env
        dest: "{{ base_dir }}/.env"
        mode: '0600' # Strict permissions for the actual token


    - name: Copy Docker Compose file
      copy:
        src: ./compose.yaml
        dest: "{{ base_dir }}/compose.yaml"

    - name: Pull and start the Docker containers
      community.docker.docker_compose_v2:
        project_src: "{{ base_dir }}"
        state: present
        pull: always