---
- name: Deploy Mgmt-Proxy Gateway
  hosts: mgmt_proxy
  become: true
  vars_files:
    - vars/services.yaml
  vars:
    cloudflared_token: "{{ lookup('ini', 'CLOUDFLARED_TOKEN type=properties file=.env') }}"
    base_dir: "/opt/services/management-proxy"

  tasks:
    - name: Ensure directories exist
      file: 
        path: "{{ item }}" 
        state: directory
        mode: '0755'
        owner: root
        group: root
      loop:
        - "{{ base_dir }}"
        - "{{ base_dir }}/conf.d"

    - name: Copy Docker Compose file, using the new .env method. Checkout "getting variable from .env without copying" in kb
      template:
        src: ./compose.yaml
        dest: "{{ base_dir }}/compose.yaml"

    - name: Copy Base Nginx Config
      copy:
        src: ./nginx.conf
        dest: "{{ base_dir }}/nginx.conf"

    - name: Update & run Nginx proxy
      import_tasks: tasks/nginx_proxy.yaml
      tags: nginx_proxy

    - name: Pull and start the Docker containers
      community.docker.docker_compose_v2:
        project_src: "{{ base_dir }}"
        files:
          - compose.yaml
        state: present
        pull: always
        recreate: always

  handlers:
    - name: Reload nginx
      shell: "docker exec nginx-proxy nginx -s reload"
