# This is a list of apps/services that are behind the reverse proxy

services:
  - name: n8n
    domain: n8n.atakan-erdonmez.com
    ip: 192.168.20.55
    port: 5678
    websockets: true

  - name: kavita
    domain: kavita.atakan-erdonmez.com
    ip: 192.168.20.50
    port: 5000
    websockets: yes

  - name: freshrss
    domain: rss.atakan-erdonmez.com
    ip: 192.168.20.50
    port: 1234
    websockets: no