# This is a list of apps/services that are behind the management proxy

#services:
#  - name: proxmox
#    domain: pve.lab.example.com
#    ip: 10.0.0.10
#    port: 8006
#    protocol: https  # Triggers SSL-verify off
#    websockets: true # Triggers 1-hour timeouts

#  - name: kavita
#    domain: kavita.atakan-erdonmez.com
#    ip: 192.168.20.50
#    port: 5000
#    websockets: yes
