---
- name: Deploy App-Proxy Gateway
  hosts: gateway
  become: true
  vars_files:
    - vars/services.yaml
  vars:
    cloudflared_token: "{{ lookup('env', 'CLOUDFLARED_TOKEN') }}"

  tasks:
    - name: Run Cloudflare Infrastructure Tasks
      import_tasks: tasks/cloudflared.yaml
      tags: infra

    - name: Run Nginx Configuration Tasks
      import_tasks: tasks/nginx.yaml
      tags: proxy

  handlers:
    - name: Restart cloudflared
      service:
        name: cloudflared
        state: restarted

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded
    
    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes