---
- name: Deploy wallabag on app01
  hosts: app01
  become: true

  vars:
    base_dir: "/opt/services/wallabag"
    nfs_server: "192.168.10.103"
    nfs_path: "/services/wallabag"
    mount_point: "/mnt/services/wallabag"
    restic_password: "{{ wallabag_restic_backup_pw }}"

  vars_files:
  - "group_vars/all/secrets.yaml"


  tasks:
    - name: Ensure base directory exists
      ansible.builtin.file:
        path: "{{ base_dir }}"
        state: directory
        owner: "1000"
        group: "1000"
        mode: "0750"

    - name: Ensure app data directories exist with nobody ownership
      ansible.builtin.file:
        path: "{{ base_dir }}/{{ item }}"
        state: directory
        owner: "65534"
        group: "65534"
        mode: "0775"
      loop:
        - data
        - images



    - name: Copy compose file
      ansible.builtin.copy:
        src: compose.yaml
        dest: "{{ base_dir }}/compose.yaml"
        owner: "1000"
        group: "1000"
        mode: "0640"

    - name: Generate & copy .env file
      ansible.builtin.template:
        src: .env.j2
        dest: "{{ base_dir }}/.env"
        owner: "1000"
        group: "1000"
        mode: "0600" # Industry standard for protecting secrets on disk


  
    - name: Deploy stack
      community.docker.docker_compose_v2:
        project_src: "{{ base_dir }}"
        state: present
        pull: always


    - name: Configure restic backup for wallabag
      ansible.builtin.include_role:
        name: restic_backup