---
- name: Deploy Kavita for e-book server
  hosts: debiandocker
  become: true
  vars:
    base_dir: "/opt/services/kavita"
    nfs_server: "192.168.10.103"
    nfs_path: "/services/kavita"
    mount_point: "/mnt/services/kavita"

  tasks:
    - name: Install NFS client dependencies
      apt:
        name:
          - nfs-common
          - rpcbind
        state: present
        update_cache: yes

    - name: Ensure local service directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: atakan
        group: atakan
      loop:
        - "{{ base_dir }}"
        - "{{ base_dir }}/config"
        - "{{ base_dir }}/data"


    - name: Configure NFS mount in fstab and mount it
      mount:
        path: "{{ mount_point }}"
        src: "{{ nfs_server }}:{{ nfs_path }}"
        fstype: nfs
        opts: "nfsvers=4.1,defaults,_netdev,noatime,timeo=600,retrans=2"
        state: mounted

    - name: Copy Docker Compose
      copy:
        src: ./compose.yaml
        dest: "{{ base_dir }}/compose.yaml"
        mode: '0644'
        owner: atakan
        group: atakan

    - name: Pull and run containers
      community.docker.docker_compose_v2:
        project_src: "{{ base_dir }}"
        state: present
        pull: always