---
- name: Deploy and configure Nginx Reverse Proxy for remote access to my homelab
  hosts: rasp
  become: true
  vars:
    base_dir: "/opt/services/management-proxy"

  tasks:
    - name: Ensure directories exist
      file: 
        path: "{{ base_dir }}" 
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Copy Nginx Configuraiton
      copy:
        src: ./nginx.conf
        dest: "{{ base_dir }}/nginx.conf"
        mode: '0644'
    
    - name: Copy Production Environment file
      copy:
        src: ./.env
        dest: "{{ base_dir }}/.env"
        mode: '0600' # Strict permissions for the actual token

    - name: Copy Environment Example file
      copy:
        src: ./.env.example
        dest: "{{ base_dir }}/.env.example"
        mode: '0644'
      
    - name: Copy Docker Compose file
      copy:
        src: ./docker-compose.yaml
        dest: "{{ base_dir }}/docker-compose.yaml"

    - name: Pull and start the Docker containers
      community.docker.docker_compose_v2:
        project_src: "{{ base_dir }}"
        state: present