# /etc/nginx/conf.d/
server {
    server_name knowledgebase.atakan-erdonmez.com;

    location / {
        root /var/www/knowledge_base;
        index index.html;
        try_files $uri $uri/ $uri.html =404;
    }

    listen 443 ssl; # managed by Certbot
    listen [::]:443 ssl; # Added for IPv6 consistency
    ssl_certificate /etc/letsencrypt/live/knowledgebase.atakan-erdonmez.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/knowledgebase.atakan-erdonmez.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    listen 80;
    listen [::]:80; # Added for IPv6 consistency
    server_name knowledgebase.atakan-erdonmez.com;

    return 301 https://$host$request_uri;
}
